import { CompetitionModel } from './src/sdk/models/competition.model';
import { UserModel } from './src/sdk/models/user.model';
import { CompetitorModel } from './src/sdk/models/competitor.model';
import { JudgeModel } from './src/sdk/models/judge.model';
import { scoreboardBaseUrl } from './src/sdk/scoreboard.sdk';
import { CompetitionSecure } from './src/modules/competition/model/competition.model';
import { CompetitorWithResultsSecure, Competitor } from './src/modules/competitor/model/competitor.model';
import { Judge, JudgeSecure } from './src/modules/judge/model/judge.model';
import { UserSecure } from './src/modules/user/model/user.model';
import { CompetitionStatus } from './src/modules/competition/model/competitionStatus.enum';
import { CompetitionPrivilege } from './src/modules/competition/model/privilege.enum';
import { CompetitorResult } from './src/modules/competition/model/result.model';
import { JudgeType } from './src/modules/judge/model/judgeType.enum';
import { Role } from './src/modules/user/model/role.enum';
import { ICompetitionCreateRequestObject, ICompetitionSetStatusRequestObject, ICompetitionEditRequestObject, ICompetitionEditRoundsRequestObject } from './modules/competition/model/data/competition.data.sdk.interface';
import { ICompetitorEditRequestObject, ICompetitorAddRequestObject, ICompetitorSetResultRequestObject } from './modules/competitor/model/data/competitor.data.sdk.interface';
import { IJudgeAddRequestObject, IJudgeEditRequestObject } from './modules/judge/model/data/judge.data.sdk.interface';
import { IUserLoginRequestObject, IUserLoginResponseObject, IUserCreateRequestObject, ILoginResponseObject, IJudgeLoginResponseObject } from './modules/user/model/data/user.data.sdk.interface';
import { IPaginationData, IPaginationResponseObject, IName, IDatePair } from './shared/model/shared.sdk.interface';
export { scoreboardBaseUrl, CompetitionModel, CompetitorModel, JudgeModel, UserModel, CompetitionSecure, ICompetitionCreateRequestObject, ICompetitionSetStatusRequestObject, ICompetitionEditRequestObject, ICompetitionEditRoundsRequestObject, CompetitionStatus, CompetitionPrivilege, Competitor, CompetitorWithResultsSecure, ICompetitorEditRequestObject, ICompetitorAddRequestObject, ICompetitorSetResultRequestObject, CompetitorResult, Judge, JudgeSecure, IJudgeAddRequestObject, IJudgeEditRequestObject, IJudgeLoginResponseObject, JudgeType, UserSecure, IUserLoginRequestObject, IUserCreateRequestObject, IUserLoginResponseObject, ILoginResponseObject, IPaginationData, IPaginationResponseObject, IName, IDatePair, Role, };
