import { CompetitionModel } from './src/sdk/models/competition.model';
import { UserModel } from './src/sdk/models/user.model';
import { CompetitorModel } from './src/sdk/models/competitor.model';
import { JudgeModel } from './src/sdk/models/judge.model';
import { scoreboardBaseUrl } from './src/sdk/scoreboard.sdk';
import { CompetitionStatus } from './src/modules/competition/model/competitionStatus.enum';
import { CompetitionPrivilege } from './src/modules/competition/model/privilege.enum';
import { CompetitorResult } from './src/modules/competition/model/result.model';
import { JudgeType } from './src/modules/judge/model/judgeType.enum';
import { Role } from './src/modules/user/model/role.enum';
import { ICompetitionCreateRequestObject, ICompetitionSetStatusRequestObject, ICompetitionEditRequestObject, ICompetitionEditRoundsRequestObject } from './src/modules/competition/model/data/competition.data.sdk.interface';
import { ICompetitorEditRequestObject, ICompetitorAddRequestObject, ICompetitorSetResultRequestObject } from './src/modules/competitor/model/data/competitor.data.sdk.interface';
import { IJudgeAddRequestObject, IJudgeEditRequestObject } from './src/modules/judge/model/data/judge.data.sdk.interface';
import { IUserLoginRequestObject, IUserLoginResponseObject, IUserCreateRequestObject, ILoginResponseObject, IJudgeLoginResponseObject } from './src/modules/user/model/data/user.data.sdk.interface';
import { IPaginationData, IPaginationResponseObject, IName, IDatePair } from './src/shared/model/shared.sdk.interface';
import { ICompetition, ICompetitionSecure, ICompetitionDetailed, ICompetitionMinimalSecure } from './src/modules/competition/model/competition.sdk.interface';
import { ICompetitorWithResultsSecure, ICompetitor } from './src/modules/competitor/model/competitor.sdk.interface';
import { IJudge, IJudgeSecure } from './src/modules/judge/model/judge.sdk.interface';
import { IUserSecure } from './src/modules/user/model/user.sdk.interface';
export { scoreboardBaseUrl, CompetitionModel, CompetitorModel, JudgeModel, UserModel, ICompetition, ICompetitionSecure, ICompetitionDetailed, ICompetitionMinimalSecure, ICompetitionCreateRequestObject, ICompetitionSetStatusRequestObject, ICompetitionEditRequestObject, ICompetitionEditRoundsRequestObject, CompetitionStatus, CompetitionPrivilege, ICompetitor, ICompetitorWithResultsSecure, ICompetitorEditRequestObject, ICompetitorAddRequestObject, ICompetitorSetResultRequestObject, CompetitorResult, IJudge, IJudgeSecure, IJudgeAddRequestObject, IJudgeEditRequestObject, IJudgeLoginResponseObject, JudgeType, IUserSecure, IUserLoginRequestObject, IUserCreateRequestObject, IUserLoginResponseObject, ILoginResponseObject, IPaginationData, IPaginationResponseObject, IName, IDatePair, Role, };
