"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const competition_model_1 = require("./sdk/models/competition.model");
exports.CompetitionModel = competition_model_1.CompetitionModel;
const user_model_1 = require("./sdk/models/user.model");
exports.UserModel = user_model_1.UserModel;
const competitor_model_1 = require("./sdk/models/competitor.model");
exports.CompetitorModel = competitor_model_1.CompetitorModel;
const judge_model_1 = require("./sdk/models/judge.model");
exports.JudgeModel = judge_model_1.JudgeModel;
const scoreboard_sdk_1 = require("./sdk/scoreboard.sdk");
exports.scoreboardBaseUrl = scoreboard_sdk_1.scoreboardBaseUrl;
const competitionStatus_enum_1 = require("./modules/competition/model/competitionStatus.enum");
exports.CompetitionStatus = competitionStatus_enum_1.CompetitionStatus;
const privilege_enum_1 = require("./modules/competition/model/privilege.enum");
exports.CompetitionPrivilege = privilege_enum_1.CompetitionPrivilege;
const result_model_1 = require("./modules/competition/model/result.model");
exports.CompetitorResult = result_model_1.CompetitorResult;
const judgeType_enum_1 = require("./modules/judge/model/judgeType.enum");
exports.JudgeType = judgeType_enum_1.JudgeType;
const role_enum_1 = require("./modules/user/model/role.enum");
exports.Role = role_enum_1.Role;
